[SYSTEM]
MaxConcurrency = 10
RetentionDays = 30

[AI]
ModelName = gemini-2.5-flash
RequestDelay = 4
Concurrency = 2

[SMTP]
# Server = smtp.gmail.com
Server = smtp.qq.com
Port = 465

[TELEGRAM]
Enabled = true